### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by achimhoth** [krzynio/python-samsung-smarttv-2016#1]
Hey mate, which TV did you test your code with?

**Comment by krzynio** [comment]
UE55KS7000SXXH

Look at the screen of your TV - you have to accept the connection when used for the first time.

**Comment by achimhoth** [comment]
Great, I will check that out. Thanks a lot for the work you've put in! Is there another source I can learn from or did you figure this out all by yourself?

**Comment by krzynio** [comment]
I used wireshark to listen to the data and then googled for some sniffed strings to find nodejs code and port it to python.

**Comment by achimhoth** [comment]
Well thanks for the effort! I will see if this works on some other 2016 models.

**Comment by davorf** [comment]
Hello!

Do you know if it's possible to make your code compatible with 2014 TVs (H series)? I've tried it as-is, but it didn't work. I don't get an authentication message on the TV and commands are not working. 

Best regards,
Davor

**Comment by krzynio** [comment]
You should use https://github.com/Ape/samsungctl and I think that they have added support for 2016+ TV so my repo is irrelevant.

**Comment by achimhoth** [comment]
```
        payload = json.dumps({
            "method": "ms.remote.control",
            "params": {
                "Cmd": "Click",
                "DataOfCmd": key,
                "Option": "false",
                "TypeOfRemote": "SendRemoteKey"
            }
        })
```

While listening to the data through wireshark, did you see other params then seen above? I was wondering if there it is possible to input text through the remote (was possible in legacy tvs) or control the cursor in a more direct way.

**Comment by achimhoth** [comment]
So I tried to Wireshark my iPhone and K-Series TV but the connection seems to be encrypted. How where you able to decrypt these conversations?

![image](https://cloud.githubusercontent.com/assets/5278493/21922205/986d9e54-d96d-11e6-8327-f4809fe6c34f.png)

**Comment by krzynio** [comment]
PORT     STATE SERVICE
7676/tcp open  imqbrokerd
8000/tcp open  http-alt
8001/tcp open  vcom-tunnel
8002/tcp open  teradataordbms
8080/tcp open  http-proxy
8899/tcp open  ospf-lite
9999/tcp open  abyss

I sniffed websocket connection and it was plaintext.
I'll try to sniff this again during the weekend. Can you tell me exact model of your TV?

**Comment by achimhoth** [comment]
Oh that would be great! On Android the Samsung Smart View App has a TouchPad and also a Keyboard for entering text in the browser. I'd love to see what happens in the Websocket when you use these.

I bought the K5579 and sniffed with my iPhone connected via USB. Maybe that is the problem.

**Comment by krzynio** [comment]
It's all encrypted now, new version of iphone app does not use websockets anymore. :(

**Comment by achimhoth** [comment]
Ah that is too bad. I'll check with the Android App but I guess that won't make a big difference.

**Comment by achimhoth** [comment]
Same on Android. It's an encrypted TCP connection on 8001 now. Hope they won't shut down support for the plain WebSocket connection in the future.

**Comment by krzynio** [comment]
iOS app connects to port 8002.

**Comment by timelery** [comment]
A command line tool I built that can send remote control commands to 2014+ Samsung TVs that use the new encrypted protocol is out on my Github repository here:

[https://github.com/timelery/NewestSamsung-RemoteControl](https://github.com/timelery/NewestSamsung-RemoteControl)

The compiled application can be ran directly after downloading the package from here:
[https://github.com/timelery/NewestSamsung-RemoteControl/tree/master/SmartTVRemoteControl/bin/x86/Release](https://github.com/timelery/NewestSamsung-RemoteControl/tree/master/SmartTVRemoteControl/bin/x86/Release)

Please provide feedback.

Thanks,
Tim

**Comment by krzynio** [comment]
@timelery Glad to read it, but can you help me with testing this on another architecture than Windows? I have no access to windows machine.
