### ISSUE TITLE
Don't work with UE48JU6400

### ISSUE THREAD

**Issue by diegodeodati** [krzynio/python-samsung-smarttv-2016#2]
Even in connection refused on port 55000.
I can't use this tool with my tv :( 

Can anyone help me ?

**Comment by krzynio** [comment]
I think that it is clear that this code works only for 2016+ TVs. Your TV is from 2015.

**Comment by diegodeodati** [comment]
Can u suggest some script to controll my tv over wifi or lan ?

**Comment by diegodeodati** [comment]
Do you know any python script to controll my tv over lan ?

UE48JU6400



Diego Deodati
Facebook Contact <http://www.facebook.com/diego.deodati>
Google Plus Contact <https://plus.google.com/u/0/102394869832154623439>
LinkedIn <http://it.linkedin.com/pub/diego-deodati/41/16b/753>


2017-01-30 14:55 GMT+01:00 Krzysztof Koziarek <notifications@github.com>:
